const mongoose = require("mongoose")

// Allow custom string IDs for lessons
const lessonSchema = new mongoose.Schema(
  {
    _id: { type: String, required: false }, // ✅ Accept string IDs or autogenerated
    title: { type: String, required: true },
    description: String,
    videoUrl: String,
    videoPublicId: String,
    thumbnailUrl: String,
    duration: { type: Number, default: 0 },
    order: { type: Number, required: true },
    isPreview: { type: Boolean, default: false },
    resources: [
      {
        title: String,
        url: String,
        publicId: String,
        type: { type: String, enum: ["pdf", "video", "link", "document", "image"] },
      },
    ],
  },
  { timestamps: true }
)

// Allow custom string IDs for modules
const moduleSchema = new mongoose.Schema(
  {
    _id: { type: String, required: false }, // ✅ Accept string IDs or autogenerated
    name: { type: String, required: true },
    subcourses: [lessonSchema],
    order: { type: Number, required: true },
  },
  { timestamps: true }
)

const reviewSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    rating: { type: Number, required: true, min: 1, max: 5 },
    comment: { type: String, required: true, maxlength: 1000 },
    isVerifiedPurchase: { type: Boolean, default: false },
  },
  { timestamps: true }
)

const courseSchema = new mongoose.Schema(
  {
    title: { type: String, required: true, trim: true, maxlength: 200 },
    description: { type: String, required: true, maxlength: 2000 },
    shortDescription: { type: String, maxlength: 500 },
    instructor: { type: String, required: true },
    instructorId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    instructorImage: String,
    instructorImagePublicId: String,
    category: {
      type: String,
      required: true,
      enum: ["Programming", "Design", "Marketing", "Business", "Creative", "Technology", "Health", "Language"],
    },
    subcategory: String,
    level: { type: String, required: true, enum: ["Beginner", "Intermediate", "Advanced"] },
    price: { type: Number, required: true, min: 0 },
    originalPrice: { type: Number, min: 0 },
    currency: { type: String, default: "INR" },
    thumbnail: { type: String, default: "https://via.placeholder.com/400x225?text=Course+Thumbnail" },
    thumbnailPublicId: String,
    thumbnailSource: { type: String, enum: ["upload", "link"], default: "upload" },
    previewVideo: String,
    previewVideoPublicId: String,
    images: [{ url: String, publicId: String }],
    duration: { type: Number, default: 0 },
    modules: [moduleSchema], // ✅ Nested modules
    totalLessons: { type: Number, default: 0 },
    requirements: [String],
    whatYouWillLearn: [String],
    targetAudience: [String],
    tags: [String],
    language: { type: String, default: "English" },
    subtitles: [String],
    rating: { type: Number, default: 0, min: 0, max: 5 },
    reviewCount: { type: Number, default: 0 },
    reviews: [reviewSchema],
    enrollmentCount: { type: Number, default: 0 },
    avgRating: { type: Number, default: 0 },
    isPublished: { type: Boolean, default: true },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    isPopular: { type: Boolean, default: false },
    isFeatured: { type: Boolean, default: false },
    publishedAt: Date,
    lastUpdated: { type: Date, default: Date.now },
    status: { type: String, enum: ["draft", "review", "published", "archived"], default: "published" },
    difficulty: { type: String, enum: ["Easy", "Medium", "Hard"], default: "Medium" },
    certificate: {
      available: { type: Boolean, default: true },
      passingScore: { type: Number, default: 70 },
    },
    seo: { metaTitle: String, metaDescription: String, keywords: [String], slug: { type: String, sparse: true } },
    analytics: { views: { type: Number, default: 0 }, completionRate: { type: Number, default: 0 }, averageWatchTime: { type: Number, default: 0 } },
  },
  { timestamps: true }
)

module.exports = mongoose.model("Course", courseSchema)
