name: Deploy to Production Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          client/package-lock.json
          server/package-lock.json
    
    - name: Install dependencies
      run: |
        npm ci
        cd client && npm ci
        cd ../server && npm ci
    
    - name: Build client
      run: |
        cd client
        npm run build
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/lmms
          git pull origin main
          
          # Install dependencies
          npm run install:all
          
          # Build client
          cd client
          npm run build
          
          # Restart server with updated environment
          cd ../server
          pm2 restart lmms-server --update-env
          
          # Check status
          pm2 status
          
          echo "✅ Deployment completed successfully!"